projects:
  pokerstudyapp:
    schemaPath: amplify/backend/api/pokerstudyapp/build/schema.graphql
    includes:
      - queries
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
